openapi: 3.0.3
info:
  title: SDDL Referral. Render at https://editor.swagger.io/
  version: 1.0.0
paths:
  /NewReferral:
    post:
      summary: Create a new referral. This is called when user taps on "Text", "Email" or "Share" button to send/share sddl with friend. 
               The return object model contains a referralId (e.g. 'r3TY') which is to be used to generate the sddl tiny url.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referral'
            example:
              referralCode: MYCODE123
      responses:
        '201':
          description: Referral created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referral'
              example:
                id: 425
                referralId: r003r
                referralCode: MYCODE123
                referrerUserId: auth0|abc123
                refereeUserId: null
                status: Pending
                createdAt: 2025-07-16T12:34:56Z
        '400':
          description: Bad request. Invalid input. Can occur if model state is invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    required:
                     - error
              example:
                error: {"code":"400","message":"Request body not supported"}
        '401':
          description: Unauthorized
        '500':
          description: Internal server error. Can occur during database failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                required:
                  - value
                example:
                  value: Object reference not set to an instance of an object

  /Referrals:
    get:
      summary: Get all user scoped referrals. In other words, returns all referrals for which the referrer is the calling user.
               This is called when user taps 'Invite Friends' to display 'My Referrals' list. User Id is derived from user token.
      security:
        - bearerAuth: []
      parameters:
        - name: $filter
          in: query
          description: OData filter expression
          schema:
            type: string
            example: status eq 'Completed'. status eq 1
        - name: $orderby
          in: query
          description: OData orderby expression
          schema:
            type: string
        - name: $top
          in: query
          description: Limit number of results
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: List of referrals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Referral'
              examples:
                example1:
                  summary: Sample response
                  value:
                    - id: 1
                      referralId: "r3TY"
                      referralCode: "MYCODE123"
                      referrerUserId: "auth0|abc123"
                      refereeUserId: "auth0|xyz456"
                      status: "Completed"
                      createdAt: "2025-07-16T12:34:56Z"
        '401':
          description: Unauthorized

  /CompleteReferral/{referralId}:
    put:
      summary: Update a referral by updating the status to 'Complete' and refereeUserId to the caller.
               This is called after referee is signed up. The newly signed up user's' token is used to derive refereeUserId.
      security:
        - bearerAuth: []
      parameters:
        - name: referralId
          in: path
          required: true
          schema:
            type: string
            example: "r3TY"
      requestBody:
        content: {}
        required: false
      responses:
        '200':
          description: Referral updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referral'
              example:
                id: 425
                referralId: r003r
                referralCode: MYCODE123
                referrerUserId: auth0|abc123
                refereeUserId: auth0|xyz234
                status: Complete
                createdAt: 2025-07-16T12:34:56Z
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Referral not found
        '500':
          description: Internal server error. Can occur during database failure.

  /Download/{referralId}:
    get:
      summary: Redirect to app store. This is the SDDL generated in client side. This is called when user taps on the link. 
               It stores an entry of the referral Id keyed by the device fingerprint. 
               It returns the fingerprint in a cookie for client app to use it to check referral on first load of the client app.
               It also returns a reditect response with a link to the app to opened/installed on client device.
      parameters:
        - name: referralId
          in: path
          required: true
          schema:
            type: string
          example: r3TY
        - name: User-Agent
          in: header
          schema:
            type: string
          example: Mozilla/5.0 (Linux; Android 11; Pixel 5)
      responses:
        '302':
          description: Redirect to app store
          headers:
            Set-Cookie:
              schema:
                type: string
              example: fpId=4bdb3a62-70e1-4a07-a56e-16db021e3848; path=/; httponly
            Location:
              schema:
                type: string
              example: https://play.google.com/store/apps/details?id=com.cartoncaps.package
        '400':
          description: Bad request. Can occur if link is expired
        '404':
          description: Referral ID not found
        '500':
          description: Internal server error. Can occur during database failure

  /ValidateReferral/{fpId}:
    get:
      summary: Validate device fingerprint for referral. This is used to check if app was downloaded on this device through a SDDL.
               It is called on first app load. The device fingerprint is fetched from stored cookie on browser where the SDDL was tapped.
      parameters:
        - name: fpId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: 4bdb3a62-70e1-4a07-a56e-16db021e3848
        - name: User-Agent
          in: header
          schema:
            type: string
          example: Mozilla/5.0 (Linux; Android 11; Pixel 5)
      responses:
        '200':
          description: Referral validated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppDownload'
              example:   
                id: 101
                fpId: 4bdb3a62-70e1-4a07-a56e-16db021e3848
                ipAddress: 192.168.1.100
                userAgent: Mozilla/5.0 (Linux; Android 11; Pixel 5)
                referralId: r3TY
                referralCode: MYCODE123
                createdAt: 2025-07-16T13:00:00Z
        '400':
          description: Validation failed (IP/UserAgent mismatch, etc) to prevent fraud or if referral is already completed to prevent double redeem
        '404':
          description: Fingerprint or referral not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Referral:
      type: object
      properties:
        id:
          type: integer
          example: 1
        referralId:
          type: string
          example: r3TY
        referralCode:
          type: string
          example: MYCODE123
        referrerUserId:
          type: string
          nullable: true
          example: auth0|abc123
        refereeUserId:
          type: string
          nullable: true
          example: auth0|xyz456
        status:
          type: string
          enum: [Pending, Completed]
          example: Pending
        createdAt:
          type: string
          format: date-time
          example: 2025-07-16T12:34:56Z
      required:
        - referralCode

    AppDownload:
      type: object
      properties:
        id:
          type: integer
          example: 101
        fpId:
          type: string
          example: 4bdb3a62-70e1-4a07-a56e-16db021e3848
        ipAddress:
          type: string
          example: 192.168.1.100
        userAgent:
          type: string
          example: Mozilla/5.0 (Linux; Android 11; Pixel 5)
        referralId:
          type: string
          example: r3TY
        referralCode:
          type: string
          example: MYCODE123
        createdAt:
          type: string
          format: date-time
          example: 2025-07-16T13:00:00Z
      required:
        - fpId
        - referralId

